service: carousel-api

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*

functions:
  uploadFile:
    handler: handler.uploadFile
    events:
      - http:
          path: uploadFile
          method: post
          cors: true